services:
  wallet:
    build: .
    container_name: bitcoin-wallet
    volumes:
      - .:/app
      - wallet-data:/app/data
      - bundle-data:/app/.bundle
    tty: true
    environment:
      - NETWORK=signet
      - DATA_DIR=/app/data

  test:
    build: .
    container_name: bitcoin-wallet-test
    volumes:
      - .:/app
      - wallet-data:/app/data
      - bundle-data:/app/.bundle
    environment:
      - NETWORK=signet
      - DATA_DIR=/app/data
    entrypoint: ["/bin/bash", "-c"]
    command: ["bundle exec rspec"]

volumes:
  wallet-data:
  bundle-data:
